server:
  port: 8080
#  servlet:
#    context-path: /templates

spring:
  profiles:
    active: local

  application:
    name: GraduationWork

  datasource:
    url: jdbc:mysql://localhost:3306/db #&dbUrl
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: admin
      password: admin

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        default_schema: db
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:db/migrations/db.changelog-master.xml
    enabled: true